// <auto-generated />
using System;
using DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250320191747_servico")]
    partial class servico
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Entities.AdminUsers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("adminuserss");
                });

            modelBuilder.Entity("DAL.Entities.Attributes", b =>
                {
                    b.Property<int>("AttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeID"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttributeID");

                    b.ToTable("attributes");
                });

            modelBuilder.Entity("DAL.Entities.Banners", b =>
                {
                    b.Property<int>("banner_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("banner_ID"), 1L, 1);

                    b.Property<string>("bnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("banner_ID");

                    b.ToTable("bannerss");
                });

            modelBuilder.Entity("DAL.Entities.Blogs", b =>
                {
                    b.Property<int>("blogid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("blogid"), 1L, 1);

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metatitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("blogid");

                    b.ToTable("Blogss");
                });

            modelBuilder.Entity("DAL.Entities.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bodytype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carmake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carmodel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fueltype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("problemtofix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servicetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shopid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subcategoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transactionnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("washtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("bookingss");
                });

            modelBuilder.Entity("DAL.Entities.Brands", b =>
                {
                    b.Property<int>("Brand_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Brand_ID"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Brand_ID");

                    b.ToTable("brandss");
                });

            modelBuilder.Entity("DAL.Entities.Carfilters", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("bodytype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fueltype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("makeimage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("carfilterss");
                });

            modelBuilder.Entity("DAL.Entities.Categories", b =>
                {
                    b.Property<int>("Categories_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Categories_ID"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Categories_ID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("DAL.Entities.Contacts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("contactss");
                });

            modelBuilder.Entity("DAL.Entities.DOD", b =>
                {
                    b.Property<int>("banner_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("banner_ID"), 1L, 1);

                    b.Property<string>("bnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dealcounter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("banner_ID");

                    b.ToTable("dods");
                });

            modelBuilder.Entity("DAL.Entities.metamain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("bnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metadesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metakeyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metatitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("metamains");
                });

            modelBuilder.Entity("DAL.Entities.OrderItems", b =>
                {
                    b.Property<int>("orderItems_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderItems_ID"), 1L, 1);

                    b.Property<int?>("Ordersorder_ID")
                        .HasColumnType("int");

                    b.Property<string>("Product_ID_custom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductsProduct_ID")
                        .HasColumnType("int");

                    b.Property<string>("cbm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_ID_custom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.Property<string>("qtyordered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("singleimage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("orderItems_ID");

                    b.HasIndex("Ordersorder_ID");

                    b.HasIndex("ProductsProduct_ID");

                    b.ToTable("OrderItemss");
                });

            modelBuilder.Entity("DAL.Entities.Orders", b =>
                {
                    b.Property<int>("order_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_ID"), 1L, 1);

                    b.Property<string>("address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datetime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstaname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordernotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalcbm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalprice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("usersid")
                        .HasColumnType("int");

                    b.Property<string>("zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("order_ID");

                    b.HasIndex("usersid");

                    b.ToTable("Orderss");
                });

            modelBuilder.Entity("DAL.Entities.Otp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"), 1L, 1);

                    b.Property<string>("Attributevalue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandsBrand_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Categories_ID")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Subid")
                        .HasColumnType("int");

                    b.Property<string>("alttag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("brand_id")
                        .HasColumnType("int");

                    b.Property<string>("brandname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("categoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cbm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cbmcalculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cl20gp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cl40gp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cl40hq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("draft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metadesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metatitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("minqty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("na")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("singleImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specificationright")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("subCategoriesSubid")
                        .HasColumnType("int");

                    b.Property<string>("subcategoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("three_d")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("variations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("width")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Product_ID");

                    b.HasIndex("BrandsBrand_ID");

                    b.HasIndex("Categories_ID");

                    b.HasIndex("subCategoriesSubid");

                    b.ToTable("productss");
                });

            modelBuilder.Entity("DAL.Entities.Queries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("queriess");
                });

            modelBuilder.Entity("DAL.Entities.rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prodid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("producttitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("DAL.Entities.ServiceCategories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("servicecategoriess");
                });

            modelBuilder.Entity("DAL.Entities.ServicePrice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("categoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servicecompanyid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servicecompanyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servicename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffless")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffmore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subcategoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("seriviceprices");
                });

            modelBuilder.Entity("DAL.Entities.Services", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("admin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("closetime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emirates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expiry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opentime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("servicess");
                });

            modelBuilder.Entity("DAL.Entities.ServiceSubcategories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Categories_ID")
                        .HasColumnType("int");

                    b.Property<string>("adminid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("categoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Categories_ID");

                    b.ToTable("servicesubcategoriess");
                });

            modelBuilder.Entity("DAL.Entities.Signup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("document1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("document2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("signups");
                });

            modelBuilder.Entity("DAL.Entities.Subcategories", b =>
                {
                    b.Property<int>("Subid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Subid"), 1L, 1);

                    b.Property<int?>("Categories_ID")
                        .HasColumnType("int");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("categoryname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Subid");

                    b.HasIndex("Categories_ID");

                    b.ToTable("subcategoriess");
                });

            modelBuilder.Entity("DAL.Entities.tyrebrand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("countrybrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countrymade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rimsize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tyremodel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("width")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tyrebrands");
                });

            modelBuilder.Entity("DAL.Entities.Tyrebrandimage", b =>
                {
                    b.Property<int>("Brand_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Brand_ID"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Brand_ID");

                    b.ToTable("tyrebrandimages");
                });

            modelBuilder.Entity("DAL.Entities.tyrebrandprice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("countrybrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countrymade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rimsize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tyremodel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("width")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tyrebrandprices");
                });

            modelBuilder.Entity("DAL.Entities.WhishList", b =>
                {
                    b.Property<int>("whishid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("whishid"), 1L, 1);

                    b.Property<int?>("ProductsProduct_ID")
                        .HasColumnType("int");

                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.Property<int?>("signupid")
                        .HasColumnType("int");

                    b.HasKey("whishid");

                    b.HasIndex("ProductsProduct_ID");

                    b.HasIndex("signupid");

                    b.ToTable("whish");
                });

            modelBuilder.Entity("DAL.Entities.OrderItems", b =>
                {
                    b.HasOne("DAL.Entities.Orders", "Orders")
                        .WithMany()
                        .HasForeignKey("Ordersorder_ID");

                    b.HasOne("DAL.Entities.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsProduct_ID");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DAL.Entities.Orders", b =>
                {
                    b.HasOne("DAL.Entities.Signup", "users")
                        .WithMany()
                        .HasForeignKey("usersid");

                    b.Navigation("users");
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.HasOne("DAL.Entities.Brands", "Brands")
                        .WithMany()
                        .HasForeignKey("BrandsBrand_ID");

                    b.HasOne("DAL.Entities.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("Categories_ID");

                    b.HasOne("DAL.Entities.Subcategories", "subCategories")
                        .WithMany()
                        .HasForeignKey("subCategoriesSubid");

                    b.Navigation("Brands");

                    b.Navigation("Categories");

                    b.Navigation("subCategories");
                });

            modelBuilder.Entity("DAL.Entities.ServiceSubcategories", b =>
                {
                    b.HasOne("DAL.Entities.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("Categories_ID");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("DAL.Entities.Subcategories", b =>
                {
                    b.HasOne("DAL.Entities.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("Categories_ID");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("DAL.Entities.WhishList", b =>
                {
                    b.HasOne("DAL.Entities.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsProduct_ID");

                    b.HasOne("DAL.Entities.Signup", "signup")
                        .WithMany()
                        .HasForeignKey("signupid");

                    b.Navigation("Products");

                    b.Navigation("signup");
                });
#pragma warning restore 612, 618
        }
    }
}
